[tool.poetry]
name = "demo-app"
version = "0.1.0"
description = "Hybrid Cloud Demo App"
authors = ["brian.perret <brian.perret@epita.fr>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.136,<0.142"
uvicorn = ">=0.45,<0.53"
psycopg2-binary = "^2.9.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
